from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 250)
        MainWindow.setMinimumSize(QtCore.QSize(500, 250))
        MainWindow.setMaximumSize(QtCore.QSize(500, 250))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/Resources/icon/main.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.homePathLabel = QtWidgets.QLabel(self.centralWidget)
        self.homePathLabel.setGeometry(QtCore.QRect(20, 100, 371, 16))
        self.homePathLabel.setOpenExternalLinks(True)
        self.homePathLabel.setObjectName("homePathLabel")
        self.logoLabel = QtWidgets.QLabel(self.centralWidget)
        self.logoLabel.setGeometry(QtCore.QRect(120, 20, 31, 31))
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap(":/icon/Resources/icon/main.ico"))
        self.logoLabel.setObjectName("logoLabel")
        self.projectNameLabel = QtWidgets.QLabel(self.centralWidget)
        self.projectNameLabel.setGeometry(QtCore.QRect(170, 20, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.projectNameLabel.setFont(font)
        self.projectNameLabel.setObjectName("projectNameLabel")
        self.introductionLabel = QtWidgets.QLabel(self.centralWidget)
        self.introductionLabel.setGeometry(QtCore.QRect(140, 60, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.introductionLabel.setFont(font)
        self.introductionLabel.setObjectName("introductionLabel")
        self.authorLabel = QtWidgets.QLabel(self.centralWidget)
        self.authorLabel.setGeometry(QtCore.QRect(45, 120, 131, 16))
        self.authorLabel.setObjectName("authorLabel")
        self.emailLabel = QtWidgets.QLabel(self.centralWidget)
        self.emailLabel.setGeometry(QtCore.QRect(54, 140, 201, 16))
        self.emailLabel.setObjectName("emailLabel")
        self.feedbackLabel = QtWidgets.QLabel(self.centralWidget)
        self.feedbackLabel.setGeometry(QtCore.QRect(20, 160, 401, 20))
        self.feedbackLabel.setObjectName("feedbackLabel")
        self.versionLabel = QtWidgets.QLabel(self.centralWidget)
        self.versionLabel.setGeometry(QtCore.QRect(420, 220, 71, 20))
        self.versionLabel.setObjectName("versionLabel")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "nxp-uuu-qt-tool"))
        self.homePathLabel.setText(_translate("MainWindow", "<html><head/><body><p>Home Path - <a href=\"https://github.com/nixgnauhcuy/nxp-uuu-qt-tool\"><span style=\" text-decoration: underline; color:#0000ff;\">https://github.com/nixgnauhcuy/nxp-uuu-qt-tool</span></a></p></body></html>"))
        self.projectNameLabel.setText(_translate("MainWindow", "nxp uuu qt tool"))
        self.introductionLabel.setText(_translate("MainWindow", "Gui tool based on mfgtools uuu."))
        self.authorLabel.setText(_translate("MainWindow", "<html><head/><body><p>Author - nixgnauhcuy</p></body></html>"))
        self.emailLabel.setText(_translate("MainWindow", "<html><head/><body><p>Email - nixgnauhcuy@gmail.com</p></body></html>"))
        self.feedbackLabel.setText(_translate("MainWindow", "<html><head/><body><p>Feedback - <a href=\"https://github.com/nixgnauhcuy/nxp-uuu-qt-tool/issues\"><span style=\" text-decoration: underline; color:#0000ff;\">https://github.com/nixgnauhcuy/nxp-uuu-qt-tool/issues</span></a></p></body></html>"))
        self.versionLabel.setText(_translate("MainWindow", "version 1.0"))
