from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(830, 520)
        MainWindow.setMinimumSize(QtCore.QSize(830, 520))
        MainWindow.setMaximumSize(QtCore.QSize(830, 520))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/Resources/icon/main.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.deviceGroupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.deviceGroupBox.setGeometry(QtCore.QRect(10, 10, 411, 121))
        self.deviceGroupBox.setObjectName("deviceGroupBox")
        self.chipLineEdit = QtWidgets.QLineEdit(self.deviceGroupBox)
        self.chipLineEdit.setGeometry(QtCore.QRect(70, 25, 133, 21))
        self.chipLineEdit.setReadOnly(True)
        self.chipLineEdit.setObjectName("chipLineEdit")
        self.chipLabel = QtWidgets.QLabel(self.deviceGroupBox)
        self.chipLabel.setGeometry(QtCore.QRect(10, 25, 24, 16))
        self.chipLabel.setObjectName("chipLabel")
        self.fastbootLabel = QtWidgets.QLabel(self.deviceGroupBox)
        self.fastbootLabel.setGeometry(QtCore.QRect(10, 52, 49, 16))
        self.fastbootLabel.setObjectName("fastbootLabel")
        self.fastbootPathLineEdit = QtWidgets.QLineEdit(self.deviceGroupBox)
        self.fastbootPathLineEdit.setGeometry(QtCore.QRect(70, 52, 251, 21))
        self.fastbootPathLineEdit.setReadOnly(True)
        self.fastbootPathLineEdit.setObjectName("fastbootPathLineEdit")
        self.fastbootPathPushButton = QtWidgets.QPushButton(self.deviceGroupBox)
        self.fastbootPathPushButton.setGeometry(QtCore.QRect(330, 50, 24, 24))
        self.fastbootPathPushButton.setMinimumSize(QtCore.QSize(24, 24))
        self.fastbootPathPushButton.setMaximumSize(QtCore.QSize(24, 24))
        self.fastbootPathPushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/Resources/img/folder.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.fastbootPathPushButton.setIcon(icon1)
        self.fastbootPathPushButton.setObjectName("fastbootPathPushButton")
        self.fastbootBurnPushButton = QtWidgets.QPushButton(self.deviceGroupBox)
        self.fastbootBurnPushButton.setGeometry(QtCore.QRect(360, 50, 28, 24))
        self.fastbootBurnPushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/Resources/img/download.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.fastbootBurnPushButton.setIcon(icon2)
        self.fastbootBurnPushButton.setObjectName("fastbootBurnPushButton")
        self.flashMemoryComboBox = QtWidgets.QComboBox(self.deviceGroupBox)
        self.flashMemoryComboBox.setGeometry(QtCore.QRect(310, 25, 91, 21))
        self.flashMemoryComboBox.setObjectName("flashMemoryComboBox")
        self.flashMemoryComboBox.addItem("")
        self.flashMemoryComboBox.addItem("")
        self.flashMemoryComboBox.addItem("")
        self.flashMemoryComboBox.addItem("")
        self.flashMemoryLabel = QtWidgets.QLabel(self.deviceGroupBox)
        self.flashMemoryLabel.setGeometry(QtCore.QRect(210, 25, 82, 16))
        self.flashMemoryLabel.setObjectName("flashMemoryLabel")
        self.statusLabel = QtWidgets.QLabel(self.deviceGroupBox)
        self.statusLabel.setGeometry(QtCore.QRect(10, 80, 34, 16))
        self.statusLabel.setObjectName("statusLabel")
        self.statusCurLabel = QtWidgets.QLabel(self.deviceGroupBox)
        self.statusCurLabel.setGeometry(QtCore.QRect(70, 80, 331, 16))
        self.statusCurLabel.setObjectName("statusCurLabel")
        self.normalGroupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.normalGroupBox.setEnabled(False)
        self.normalGroupBox.setGeometry(QtCore.QRect(10, 140, 411, 171))
        self.normalGroupBox.setObjectName("normalGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.normalGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.deviceTreePathLineEdit = QtWidgets.QLineEdit(self.normalGroupBox)
        self.deviceTreePathLineEdit.setReadOnly(True)
        self.deviceTreePathLineEdit.setObjectName("deviceTreePathLineEdit")
        self.gridLayout_2.addWidget(self.deviceTreePathLineEdit, 3, 1, 1, 1)
        self.rootfsLabel = QtWidgets.QLabel(self.normalGroupBox)
        self.rootfsLabel.setObjectName("rootfsLabel")
        self.gridLayout_2.addWidget(self.rootfsLabel, 4, 0, 1, 1)
        self.kernelPathLineEdit = QtWidgets.QLineEdit(self.normalGroupBox)
        self.kernelPathLineEdit.setReadOnly(True)
        self.kernelPathLineEdit.setObjectName("kernelPathLineEdit")
        self.gridLayout_2.addWidget(self.kernelPathLineEdit, 2, 1, 1, 1)
        self.kernelLabel = QtWidgets.QLabel(self.normalGroupBox)
        self.kernelLabel.setObjectName("kernelLabel")
        self.gridLayout_2.addWidget(self.kernelLabel, 2, 0, 1, 1)
        self.rootfsPathLineEdit = QtWidgets.QLineEdit(self.normalGroupBox)
        self.rootfsPathLineEdit.setReadOnly(True)
        self.rootfsPathLineEdit.setObjectName("rootfsPathLineEdit")
        self.gridLayout_2.addWidget(self.rootfsPathLineEdit, 4, 1, 1, 1)
        self.kernelPathPushButton = QtWidgets.QPushButton(self.normalGroupBox)
        self.kernelPathPushButton.setMinimumSize(QtCore.QSize(24, 24))
        self.kernelPathPushButton.setMaximumSize(QtCore.QSize(24, 24))
        self.kernelPathPushButton.setText("")
        self.kernelPathPushButton.setIcon(icon1)
        self.kernelPathPushButton.setObjectName("kernelPathPushButton")
        self.gridLayout_2.addWidget(self.kernelPathPushButton, 2, 2, 1, 1)
        self.ubootBurnPushButton = QtWidgets.QPushButton(self.normalGroupBox)
        self.ubootBurnPushButton.setText("")
        self.ubootBurnPushButton.setIcon(icon2)
        self.ubootBurnPushButton.setObjectName("ubootBurnPushButton")
        self.gridLayout_2.addWidget(self.ubootBurnPushButton, 1, 3, 1, 1)
        self.rootfsBurnPushButton = QtWidgets.QPushButton(self.normalGroupBox)
        self.rootfsBurnPushButton.setText("")
        self.rootfsBurnPushButton.setIcon(icon2)
        self.rootfsBurnPushButton.setObjectName("rootfsBurnPushButton")
        self.gridLayout_2.addWidget(self.rootfsBurnPushButton, 4, 3, 1, 1)
        self.rootfsPathPushButton = QtWidgets.QPushButton(self.normalGroupBox)
        self.rootfsPathPushButton.setMinimumSize(QtCore.QSize(24, 24))
        self.rootfsPathPushButton.setMaximumSize(QtCore.QSize(24, 24))
        self.rootfsPathPushButton.setText("")
        self.rootfsPathPushButton.setIcon(icon1)
        self.rootfsPathPushButton.setObjectName("rootfsPathPushButton")
        self.gridLayout_2.addWidget(self.rootfsPathPushButton, 4, 2, 1, 1)
        self.ubootPathLineEdit = QtWidgets.QLineEdit(self.normalGroupBox)
        self.ubootPathLineEdit.setReadOnly(True)
        self.ubootPathLineEdit.setObjectName("ubootPathLineEdit")
        self.gridLayout_2.addWidget(self.ubootPathLineEdit, 1, 1, 1, 1)
        self.deviceTreePathPushButton = QtWidgets.QPushButton(self.normalGroupBox)
        self.deviceTreePathPushButton.setMinimumSize(QtCore.QSize(24, 24))
        self.deviceTreePathPushButton.setMaximumSize(QtCore.QSize(24, 24))
        self.deviceTreePathPushButton.setText("")
        self.deviceTreePathPushButton.setIcon(icon1)
        self.deviceTreePathPushButton.setObjectName("deviceTreePathPushButton")
        self.gridLayout_2.addWidget(self.deviceTreePathPushButton, 3, 2, 1, 1)
        self.deviceTreeLabel = QtWidgets.QLabel(self.normalGroupBox)
        self.deviceTreeLabel.setObjectName("deviceTreeLabel")
        self.gridLayout_2.addWidget(self.deviceTreeLabel, 3, 0, 1, 1)
        self.kernelBurnPushButton = QtWidgets.QPushButton(self.normalGroupBox)
        self.kernelBurnPushButton.setText("")
        self.kernelBurnPushButton.setIcon(icon2)
        self.kernelBurnPushButton.setObjectName("kernelBurnPushButton")
        self.gridLayout_2.addWidget(self.kernelBurnPushButton, 2, 3, 1, 1)
        self.ubootPathPushButton = QtWidgets.QPushButton(self.normalGroupBox)
        self.ubootPathPushButton.setMinimumSize(QtCore.QSize(24, 24))
        self.ubootPathPushButton.setMaximumSize(QtCore.QSize(24, 24))
        self.ubootPathPushButton.setText("")
        self.ubootPathPushButton.setIcon(icon1)
        self.ubootPathPushButton.setObjectName("ubootPathPushButton")
        self.gridLayout_2.addWidget(self.ubootPathPushButton, 1, 2, 1, 1)
        self.ubootLabel = QtWidgets.QLabel(self.normalGroupBox)
        self.ubootLabel.setObjectName("ubootLabel")
        self.gridLayout_2.addWidget(self.ubootLabel, 1, 0, 1, 1)
        self.deviceTreeBurnPushButton = QtWidgets.QPushButton(self.normalGroupBox)
        self.deviceTreeBurnPushButton.setText("")
        self.deviceTreeBurnPushButton.setIcon(icon2)
        self.deviceTreeBurnPushButton.setObjectName("deviceTreeBurnPushButton")
        self.gridLayout_2.addWidget(self.deviceTreeBurnPushButton, 3, 3, 1, 1)
        self.deviceGroupBox_3 = QtWidgets.QGroupBox(self.centralWidget)
        self.deviceGroupBox_3.setGeometry(QtCore.QRect(10, 320, 411, 141))
        self.deviceGroupBox_3.setObjectName("deviceGroupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.deviceGroupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.logGroupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.logGroupBox.setGeometry(QtCore.QRect(430, 10, 381, 451))
        self.logGroupBox.setObjectName("logGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.logGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.logPlainTextEdit = QtWidgets.QPlainTextEdit(self.logGroupBox)
        self.logPlainTextEdit.setReadOnly(True)
        self.logPlainTextEdit.setObjectName("logPlainTextEdit")
        self.gridLayout.addWidget(self.logPlainTextEdit, 0, 0, 1, 1)
        self.clearLogPushButton = QtWidgets.QPushButton(self.logGroupBox)
        self.clearLogPushButton.setObjectName("clearLogPushButton")
        self.gridLayout.addWidget(self.clearLogPushButton, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 830, 21))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "nxp-uuu-qt-tool"))
        self.deviceGroupBox.setTitle(_translate("MainWindow", "Device"))
        self.chipLabel.setText(_translate("MainWindow", "chip"))
        self.fastbootLabel.setText(_translate("MainWindow", "fastboot"))
        self.flashMemoryComboBox.setItemText(0, _translate("MainWindow", "EMMC"))
        self.flashMemoryComboBox.setItemText(1, _translate("MainWindow", "SDCARD"))
        self.flashMemoryComboBox.setItemText(2, _translate("MainWindow", "NANDFLASH"))
        self.flashMemoryComboBox.setItemText(3, _translate("MainWindow", "NORFLASH"))
        self.flashMemoryLabel.setText(_translate("MainWindow", "Flash Memory"))
        self.statusLabel.setText(_translate("MainWindow", "status"))
        self.statusCurLabel.setText(_translate("MainWindow", "No connect device!"))
        self.normalGroupBox.setTitle(_translate("MainWindow", "Normal"))
        self.rootfsLabel.setText(_translate("MainWindow", "rootfs"))
        self.kernelLabel.setText(_translate("MainWindow", "kernel"))
        self.deviceTreeLabel.setText(_translate("MainWindow", "device tree"))
        self.ubootLabel.setText(_translate("MainWindow", "uboot"))
        self.deviceGroupBox_3.setTitle(_translate("MainWindow", "Advanced"))
        self.logGroupBox.setTitle(_translate("MainWindow", "Output"))
        self.clearLogPushButton.setText(_translate("MainWindow", "Clear"))
        self.menu.setTitle(_translate("MainWindow", "About"))
